# Generated by Django 4.2.13 on 2026-06-23 18:01

from django.db import migrations, models


def converter_admin_para_manager(apps, schema_editor):
    Perfil = apps.get_model('accounts', 'Perfil')
    Perfil.objects.filter(tipo='ADMIN').update(tipo='MANAGER')


def reverter_manager_para_admin(apps, schema_editor):
    Perfil = apps.get_model('accounts', 'Perfil')
    Perfil.objects.filter(tipo='MANAGER').update(tipo='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            converter_admin_para_manager,
            reverter_manager_para_admin,
        ),
        migrations.AlterField(
            model_name="perfil",
            name="tipo",
            field=models.CharField(
                choices=[("MANAGER", "Gerente"), ("COMMON", "Comum")],
                default="COMMON",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]