# Generated by Django 6.0.6 on 2026-06-15 14:27

import cadastro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_documentoexterno_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroBolsista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
                (
                    "data_nascimento",
                    models.DateField(
                        validators=[cadastro.models.validar_maioridade],
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "grau_academico",
                    models.CharField(
                        choices=[
                            ("fundamental", "Ensino Fundamental"),
                            ("medio", "Ensino Médio"),
                            ("superior", "Ensino Superior"),
                            ("pos", "Pós-Graduação"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            ("pos_doutorado", "Pós-Doutorado"),
                        ],
                        max_length=20,
                        verbose_name="Grau acadêmico",
                    ),
                ),
                (
                    "curriculo",
                    models.FileField(
                        blank=True, upload_to="curriculos/", verbose_name="Currículo"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, upload_to="fotos/", verbose_name="Foto"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadastros",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadastro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro de Bolsista",
                "verbose_name_plural": "Cadastros de Bolsistas",
            },
        ),
        migrations.CreateModel(
            name="CursoSuperior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "instituicao",
                    models.CharField(max_length=255, verbose_name="Instituição"),
                ),
                ("curso", models.CharField(max_length=255, verbose_name="Curso")),
                (
                    "grau",
                    models.CharField(
                        choices=[
                            ("tecnologo", "Tecnólogo"),
                            ("bacharelado", "Bacharelado"),
                            ("licenciatura", "Licenciatura"),
                        ],
                        max_length=20,
                        verbose_name="Grau",
                    ),
                ),
                (
                    "ano_conclusao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de conclusão"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_superiores",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_superiores",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso Superior",
                "verbose_name_plural": "Cursos Superiores",
            },
        ),
        migrations.CreateModel(
            name="PosGraduacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pos_graduacao", "Pós-Graduação"),
                            ("mba", "MBA"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            ("pos_doutorado", "Pós-Doutorado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "instituicao",
                    models.CharField(max_length=255, verbose_name="Instituição"),
                ),
                ("area", models.CharField(max_length=255, verbose_name="Área")),
                (
                    "ano_conclusao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de conclusão"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_graduacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_graduacoes",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pós-Graduação",
                "verbose_name_plural": "Pós-Graduações",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoEdicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("campo", models.CharField(max_length=100, verbose_name="Campo")),
                ("valor_original", models.TextField(verbose_name="Valor original")),
                ("valor_novo", models.TextField(verbose_name="Valor novo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_revisao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de revisão"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_edicao",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Edição",
                "verbose_name_plural": "Solicitações de Edição",
            },
        ),
    ]
