# Generated by Django 6.0.6 on 2026-06-18 15:14

import cadastro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroBolsista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        validators=[cadastro.models.validar_maioridade],
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "rua",
                    models.CharField(blank=True, max_length=255, verbose_name="Rua"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=255, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=255, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--- Selecione ---"),
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "curriculo",
                    models.FileField(
                        blank=True, upload_to="curriculos/", verbose_name="Currículo"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, upload_to="fotos/", verbose_name="Foto"
                    ),
                ),
                (
                    "participacao_projetos_anos",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Anos de experiência em projetos/pesquisa",
                    ),
                ),
                (
                    "participacao_congressos",
                    models.BooleanField(
                        default=False,
                        verbose_name="Participação em congressos, feiras, eventos e palestras",
                    ),
                ),
                (
                    "resumo_anais",
                    models.BooleanField(
                        default=False,
                        verbose_name="Resumo publicado em anais de eventos",
                    ),
                ),
                (
                    "artigo_completo_anais",
                    models.BooleanField(
                        default=False,
                        verbose_name="Artigo completo publicado em anais de eventos",
                    ),
                ),
                (
                    "artigo_cientifico_nacional",
                    models.BooleanField(
                        default=False,
                        verbose_name="Artigo científico ou capítulo de livro nacional publicado",
                    ),
                ),
                (
                    "artigo_cientifico_internacional",
                    models.BooleanField(
                        default=False,
                        verbose_name="Artigo científico ou capítulo de livro internacional publicado",
                    ),
                ),
                (
                    "livro_patente",
                    models.BooleanField(
                        default=False,
                        verbose_name="Livro publicado na área de interesse ou patente registrada",
                    ),
                ),
                (
                    "participacao_minicurso",
                    models.BooleanField(
                        default=False,
                        verbose_name="Participação em minicurso (até 4 horas) na área de interesse",
                    ),
                ),
                (
                    "treinamento",
                    models.BooleanField(
                        default=False,
                        verbose_name="Treinamento (acima de 4 horas) na área de interesse",
                    ),
                ),
                (
                    "pontuacao_previa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Pontuação prévia",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadastros",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadastro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro de Bolsista",
                "verbose_name_plural": "Cadastros de Bolsistas",
            },
        ),
        migrations.CreateModel(
            name="FormacaoAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ensino_medio", "Ensino Médio Completo"),
                            ("graduacao", "Graduação"),
                            ("curso_tecnico", "Curso Técnico"),
                            ("especializacao", "Especialização"),
                            ("pos_graduacao", "Pós-Graduação"),
                            ("mba", "MBA"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            ("pos_doutorado", "Pós-Doutorado"),
                        ],
                        max_length=20,
                        verbose_name="Formação Acadêmica",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---"),
                            ("em_andamento", "Em Andamento"),
                            ("concluida", "Concluída"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "instituicao",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "curso",
                    models.CharField(blank=True, max_length=255, verbose_name="Curso"),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=255, verbose_name="Área"),
                ),
                (
                    "ano_conclusao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de conclusão"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formacoes",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formação Acadêmica",
                "verbose_name_plural": "Formações Acadêmicas",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoEdicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("campo", models.CharField(max_length=100, verbose_name="Campo")),
                ("valor_original", models.TextField(verbose_name="Valor original")),
                ("valor_novo", models.TextField(verbose_name="Valor novo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_revisao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de revisão"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_edicao",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Edição",
                "verbose_name_plural": "Solicitações de Edição",
            },
        ),
    ]
