# Generated by Django 4.2.13 on 2026-06-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formacaoacademica",
            name="instituicao",
        ),
        migrations.CreateModel(
            name="ExperienciaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "area_atuacao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Área de Atuação"
                    ),
                ),
                (
                    "anos_experiencia",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anos de Experiência"
                    ),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        upload_to="experiencias/",
                        verbose_name="Comprovante (PDF)",
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiência Profissional",
                "verbose_name_plural": "Experiências Profissionais",
            },
        ),
        migrations.CreateModel(
            name="AnexoComprobatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rg_cpf", "Documento de Identificação (RG/CPF)"),
                            ("comprovante_endereco", "Comprovante de Endereço"),
                            (
                                "participacao_congressos",
                                "Participação em congressos, feiras, eventos e palestras",
                            ),
                            ("resumo_anais", "Resumo publicado em anais de eventos"),
                            (
                                "artigo_completo_anais",
                                "Artigo completo publicado em anais de eventos",
                            ),
                            (
                                "artigo_cientifico_nacional",
                                "Artigo científico ou capítulo de livro nacional publicado",
                            ),
                            (
                                "artigo_cientifico_internacional",
                                "Artigo científico ou capítulo de livro internacional publicado",
                            ),
                            (
                                "livro_patente",
                                "Livro publicado na área de interesse ou patente registrada",
                            ),
                            (
                                "participacao_minicurso",
                                "Participação em minicurso (até 4 horas) na área de interesse",
                            ),
                            (
                                "treinamento",
                                "Treinamento (acima de 4 horas) na área de interesse",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "anexo",
                    models.FileField(upload_to="anexos/", verbose_name="Anexo (PDF)"),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo Comprobatório",
                "verbose_name_plural": "Anexos Comprobatórios",
            },
        ),
    ]
