# Generated by Django 6.0.6 on 2026-06-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edital_provisorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="detalhes_qualificacao_minima",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Qualificação Mínima em:",
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="modalidade_atuacao",
            field=models.CharField(
                choices=[("presencial", "Presencial"), ("remota", "Remota")],
                default="presencial",
                max_length=50,
                verbose_name="Modalidade de Atuação",
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="valor_bolsa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor da Bolsa (R$)",
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="valor_maximo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Máximo (R$)",
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="valor_minimo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Mínimo (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="email_solicitante",
            field=models.EmailField(
                help_text="Insira o seu e-mail",
                max_length=254,
                verbose_name="E-mail do Solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="experiencia_minima",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Experiência Mínima (Profissional/Acadêmica)",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="modalidade_bolsa",
            field=models.CharField(
                choices=[
                    ("nivel_1", "Nível 1"),
                    ("nivel_2", "Nível 2"),
                    ("nivel_3", "Nível 3"),
                    ("nivel_4", "Nível 4"),
                ],
                max_length=50,
                verbose_name="Modalidade da Bolsa",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="nome_instituto",
            field=models.CharField(
                choices=[
                    ("isi_biomassa", "ISI Biomassa"),
                    ("ist_alimentos", "IST Alimentos e Bebidas"),
                    ("ist_construcao", "Faculdade da Construção"),
                    ("fatec_cg", "FATEC - Campo Grande"),
                    ("departamento_regional", "DR"),
                ],
                help_text="Selecione o Instituto",
                max_length=255,
                verbose_name="Nome do Instituto",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="qualificacao_minima",
            field=models.CharField(max_length=255, verbose_name="Qualificação Mínima"),
        ),
    ]
