# Generated by Django 6.0.6 on 2026-06-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_perfil_data_nascimento"),
        (
            "edital_provisorio",
            "0002_editalprovisorio_detalhes_qualificacao_minima_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="valor_total_bolsa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor Total da Bolsa (R$)",
            ),
        ),
        migrations.CreateModel(
            name="DistribuicaoBolsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "experiencia",
                    models.CharField(max_length=255, verbose_name="Experiência"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade de Bolsistas"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuicoes",
                        to="edital_provisorio.editalprovisorio",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuicoes_provisorias",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuição de Bolsa",
                "verbose_name_plural": "Distribuições de Bolsa",
            },
        ),
    ]
