# Generated by Django 6.0.6 on 2026-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edital_provisorio",
            "0003_editalprovisorio_valor_total_bolsa_distribuicaobolsa",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="editalprovisorio",
            name="endereco_atuacao",
            field=models.TextField(
                blank=True, default="", verbose_name="Endereço de Atuação"
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="vigencia",
            field=models.PositiveIntegerField(
                default=180,
                help_text="Mínimo: 15 dias. Máximo: 36 meses (1095 dias).",
                verbose_name="Vigência (dias)",
            ),
        ),
    ]
