# Generated by Django 4.2.13 on 2026-06-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edital_provisorio", "0004_alter_editalprovisorio_endereco_atuacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editalprovisorio",
            name="experiencia_minima",
        ),
    ]
