# Generated by Django 4.2.13 on 2026-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edital_provisorio", "0005_remove_editalprovisorio_experiencia_minima"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="area_estudo",
            field=models.CharField(
                default="", max_length=255, verbose_name="Área de Estudo"
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="detalhes_edital",
            field=models.TextField(
                blank=True, default="", verbose_name="Detalhes do Edital"
            ),
        ),
        migrations.AddField(
            model_name="editalprovisorio",
            name="nome_edital",
            field=models.CharField(
                default="", max_length=255, verbose_name="Nome do Edital"
            ),
        ),
    ]
