# Generated by Django 4.2.13 on 2026-06-17 21:16

from django.db import migrations


def update_status(apps, schema_editor):
    EditalProvisorio = apps.get_model('edital_provisorio', 'EditalProvisorio')
    EditalProvisorio.objects.filter(status='rascunho').update(status='em_analise')
    EditalProvisorio.objects.filter(status='publicado').update(status='aberto')


class Migration(migrations.Migration):

    dependencies = [
        ("edital_provisorio", "0006_add_edital_info"),
    ]

    operations = [
        migrations.RunPython(update_status, migrations.RunPython.noop),
    ]
