# Generated by Django 6.0.6 on 2026-06-15 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_documentoexterno_tenant"),
        ("cadastro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Edital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("requisitos", models.TextField(verbose_name="Requisitos")),
                (
                    "data_abertura",
                    models.DateTimeField(verbose_name="Data de abertura"),
                ),
                (
                    "data_fechamento",
                    models.DateTimeField(verbose_name="Data de fechamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("fechado", "Fechado"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="aberto",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editais_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editais",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edital",
                "verbose_name_plural": "Editais",
                "ordering": ["-data_abertura"],
            },
        ),
        migrations.CreateModel(
            name="AplicacaoEdital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aplicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de aplicação"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="editais.edital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicação em Edital",
                "verbose_name_plural": "Aplicações em Editais",
                "unique_together": {("bolsista", "edital")},
            },
        ),
    ]
