# Generated by Django 6.0.6 on 2026-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aplicacaoedital",
            name="nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nota do avaliador",
            ),
        ),
    ]
