# Generated by Django 4.2.13 on 2026-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0002_add_nota_aplicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="documento_anexo",
            field=models.FileField(
                blank=True,
                upload_to="editais/",
                verbose_name="Termo de Parceria e/ou Plano de Projeto (PDF)",
            ),
        ),
    ]
