# Generated by Django 6.0.6 on 2026-06-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("classificacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificacaocriterio",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classificacao_criterios",
                to="accounts.tenant",
            ),
        ),
    ]
