# Generated by Django 6.0.6 on 2026-06-19 14:40

import django.db.models.deletion
from django.db import migrations, models


def populate_classificacaocriterio_tenant(apps, schema_editor):
    ClassificacaoCriterio = apps.get_model('classificacao', 'ClassificacaoCriterio')
    for obj in ClassificacaoCriterio.objects.select_related('classificacao__tenant').all():
        if obj.tenant_id is None and obj.classificacao and obj.classificacao.tenant_id:
            obj.tenant_id = obj.classificacao.tenant_id
            obj.save(update_fields=['tenant_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("classificacao", "0002_add_tenant_to_classificacaocriterio"),
    ]

    operations = [
        migrations.RunPython(populate_classificacaocriterio_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="classificacaocriterio",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classificacao_criterios",
                to="accounts.tenant",
            ),
        ),
    ]